# Generated by Django 5.1.7 on 2025-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_estado_remove_post_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('P', 'Publicado')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_de_publicacion',
            field=models.DateField(auto_now_add=True, default=None, null=True, blank=True),
            preserve_default=False,
        ),
    ]